package com.bottomline.SyntheticData;

public enum DistType{CAUCHY,// CONSTANTREAL, EMPIRICAL, 
	//ENUMERATED, EXPONENTIAL, F, GAMMA, GUMBEL, LAPLACE, LEVY, LOGISTIC, 
	NORMAL}//, PARETO, T, TRIANGULAR, UNIFORMREAL, WEIBULL}